use getopts to parse args

diff --git a/src/bin/sysreport b/src/bin/sysreport
--- a/src/bin/sysreport
+++ b/src/bin/sysreport
@@ -2,17 +2,20 @@
 
 [ -z "$PLUGIN_PATH" ] && PLUGIN_PATH=/usr/local/share/sysreport/plugins/$(uname)
 
-usage="sysreport [-s]"
-silent=0
+usage="usage: sysreport [-hsV]"
 worst_status=0
+VERSION=0.0.1
 
-if [ "$#" -eq 1 ] && [ "$1" == "-s" ]; then
-    silent=1
-elif [ "$#" -gt 0 ]; then
-    echo "error: invalid argument(s)"
-    echo "$usage"
-    exit 1
-fi
+
+silent="0"
+while getopts hsV flag; do
+    case "$flag" in
+        h) echo "$usage" && exit 0 ;;
+        s) silent="1" ;;
+        V) echo $VERSION && exit 0 ;;
+        ?) echo "invalid argument" 1>&2 && exit 1
+    esac
+done
 
 get_status_text() {
     case "$1" in
